name: browser-automation-service

services:
  backend:
    labels:
      infra.environment: production
    networks: !override
      browser-automation-internal:
      postgres-network:
      redis-network:
      proxy-network:
        aliases:
          - browser-automation-service
      browser-automation-network:
        aliases:
          - browser-automation-service
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - postgres_password
      - redis_password
      - api_key
      - aws_access_key_id
      - aws_secret_access_key

  dispatcher:
    labels:
      infra.environment: production
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - postgres_password
      - redis_password
      - aws_access_key_id
      - aws_secret_access_key

  worker-playwright:
    labels:
      infra.environment: production
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - postgres_password
      - redis_password
      - aws_access_key_id
      - aws_secret_access_key

  worker-puppeteer:
    labels:
      infra.environment: production
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - postgres_password
      - redis_password
      - aws_access_key_id
      - aws_secret_access_key

  worker-selenium:
    labels:
      infra.environment: production
    environment:
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
    secrets:
      - postgres_password
      - redis_password
      - aws_access_key_id
      - aws_secret_access_key

secrets:
  aws_access_key_id:
    environment: AWS_ACCESS_KEY_ID
  aws_secret_access_key:
    environment: AWS_SECRET_ACCESS_KEY
